name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    with:
      ruby-version: 2.7
      bundler-cache: true
    - name: buildit
      run: script/cibuild
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
